[disable api call + shell on falco and remove cronjob lldap]

diff --git a/clusters/infrastructure/prod/security/ldap/cronjobs.yaml b/clusters/infrastructure/prod/security/ldap/cronjobs.yaml
--- a/clusters/infrastructure/prod/security/ldap/cronjobs.yaml
+++ b/clusters/infrastructure/prod/security/ldap/cronjobs.yaml
@@ -1,113 +1,110 @@
-apiVersion: batch/v1
-kind: CronJob
-metadata:
-  name: check-lldap
-  namespace: lldap
-spec:
-  schedule: "0 8 * * *" 
-  successfulJobsHistoryLimit: 0
-  failedJobsHistoryLimit: 0
-  jobTemplate:
-    spec:
-      template:
-        spec:
-          restartPolicy: Never
-          containers:
-          - name: ldap-checker
-            image: alpine:latest
-            command:
-            - /bin/sh
-            - -c
-            - |
-              apk add --no-cache openldap-clients curl mailx
-              RESULT=$(ldapsearch \
-                -H ldap://lldap-ldap.lldap.svc.cluster.local:3890 \
-                -D "uid=admin,ou=people,dc=example,dc=com" \
-                -w "$LDAP_ADMIN_PASSWORD" \
-                -b "ou=people,dc=example,dc=com" \
-                "(uid=${LDAP_USER1_ID})" \
-                dn 2>&1)
-              echo "LDAP: $RESULT"
-              if echo "$RESULT" | grep -q "uid=${LDAP_USER1_ID}"; then
-                echo "✅ User ${LDAP_USER1_ID} find in LDAP"
-              else
-                echo "❌ Utilisateur ${LDAP_USER1_ID} introuvable - Envoi de l'alerte mail..."
-              fi
+# apiVersion: batch/v1
+# kind: CronJob
+# metadata:
+#   name: check-lldap
+#   namespace: lldap
+# spec:
+#   schedule: "0 8 * * *" 
+#   successfulJobsHistoryLimit: 0
+#   failedJobsHistoryLimit: 0
+#   jobTemplate:
+#     spec:
+#       template:
+#         spec:
+#           restartPolicy: Never
+#           containers:
+#           - name: ldap-checker
+#             image: alpine:latest
+#             command:
+#             - /bin/sh
+#             - -c
+#             - |
+#               apk add --no-cache openldap-clients curl mailx
+#               RESULT=$(ldapsearch \
+#                 -H ldap://lldap-ldap.lldap.svc.cluster.local:3890 \
+#                 -D "uid=admin,ou=people,dc=example,dc=com" \
+#                 -w "$LDAP_ADMIN_PASSWORD" \
+#                 -b "ou=people,dc=example,dc=com" \
+#                 "(uid=${LDAP_USER1_ID})" \
+#                 dn 2>&1)
+#               echo "LDAP: $RESULT"
+#               if echo "$RESULT" | grep -q "uid=${LDAP_USER1_ID}"; then
+#                 echo "✅ User ${LDAP_USER1_ID} find in LDAP"
+#               else
+#                 echo "❌ Utilisateur ${LDAP_USER1_ID} introuvable - Envoi de l'alerte mail..."
+#               fi
 
-              RESULT_GROUP=$(ldapsearch \
-                -H ldap://lldap-ldap.lldap.svc.cluster.local:3890 \
-                -D "uid=admin,ou=people,dc=example,dc=com" \
-                -w "$LDAP_ADMIN_PASSWORD" \
-                -b "ou=groups,dc=example,dc=com" \
-                "(cn=$LLDAP_GROUP)" \
-                dn 2>&1)
+#               RESULT_GROUP=$(ldapsearch \
+#                 -H ldap://lldap-ldap.lldap.svc.cluster.local:3890 \
+#                 -D "uid=admin,ou=people,dc=example,dc=com" \
+#                 -w "$LDAP_ADMIN_PASSWORD" \
+#                 -b "ou=groups,dc=example,dc=com" \
+#                 "(cn=$LLDAP_GROUP)" \
+#                 dn 2>&1)
 
-              echo "LDAP group: $RESULT_GROUP"
+#               echo "LDAP group: $RESULT_GROUP"
 
-              if echo "$RESULT_GROUP" | grep -q "^dn: cn=$LLDAP_GROUP,"; then
-                echo "✅ Groupe $LLDAP_GROUP trouvé dans LDAP"
-                exit 0
-              else
-                echo "❌ Groupe $LLDAP_GROUP introuvable"
-              fi
+#               if echo "$RESULT_GROUP" | grep -q "^dn: cn=$LLDAP_GROUP,"; then
+#                 echo "✅ Groupe $LLDAP_GROUP trouvé dans LDAP"
+#                 exit 0
+#               else
+#                 echo "❌ Groupe $LLDAP_GROUP introuvable"
+#               fi
 
-                curl \
-                  --url "smtp://$SMTP_HOST:$SMTP_PORT" \
-                  --user "test:test" \
-                  --mail-from "$MAIL_FROM" \
-                  --mail-rcpt "$MAIL_TO" \
-                  --upload-file - <<EOF
-              From: $MAIL_FROM
-              To: $MAIL_TO
-              Subject: [ALERTE] LDAP
-              Content-Type: text/plain; charset=UTF-8
+#                 curl \
+#                   --url "smtp://$SMTP_HOST:$SMTP_PORT" \
+#                   --user "test:test" \
+#                   --mail-from "$MAIL_FROM" \
+#                   --mail-rcpt "$MAIL_TO" \
+#                   --upload-file - <<EOF
+#               From: $MAIL_FROM
+#               To: $MAIL_TO
+#               Subject: [ALERTE] LDAP
+#               Content-Type: text/plain; charset=UTF-8
 
-              Bonjour,
+#               Bonjour,
 
-              Erreur dans l'annuaire LDAP.
+#               Erreur dans l'annuaire LDAP.
 
-              Filtre   : (uid=${LDAP_USER1_ID})(groups=$LLDAP_GROUP)
+#               Filtre   : (uid=${LDAP_USER1_ID})(groups=$LLDAP_GROUP)
 
-              Merci de vérifier l'annuaire LDAP.
+#               Merci de vérifier l'annuaire LDAP.
 
-              -- 
-              Kubernetes Job Monitor
-              EOF
+#               -- 
+#               Kubernetes Job Monitor
+#               EOF
 
-                if [ $? -eq 0 ]; then
-                  echo "📧 Mail envoyé avec succès"
-                else
-                  echo "💥 Échec de l'envoi du mail"
-                  exit 1
-                fi
+#                 if [ $? -eq 0 ]; then
+#                   echo "📧 Mail envoyé avec succès"
+#                 else
+#                   echo "💥 Échec de l'envoi du mail"
+#                   exit 1
+#                 fi
 
-                exit 2
-              fi
-            env:
-            - name: LDAP_ADMIN_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: lldap-credentials
-                  key: ldapUserPass
-            - name: SMTP_HOST
-              value: "maildev-smtp.maildev"
-            - name: SMTP_PORT
-              value: "1025"
-            - name: MAIL_FROM
-              value: "alertes@example.com"
-            - name: MAIL_TO
-              value: "${LDAP_USER1_EMAIL}"
-            - name: LLDAP_GROUP
-              value: "jelly_admin"
-      backoffLimit: 0
+#                 exit 2
+#               fi
+#             env:
+#             - name: LDAP_ADMIN_PASSWORD
+#               valueFrom:
+#                 secretKeyRef:
+#                   name: lldap-credentials
+#                   key: ldapUserPass
+#             - name: SMTP_HOST
+#               value: "maildev-smtp.maildev"
+#             - name: SMTP_PORT
+#               value: "1025"
+#             - name: MAIL_FROM
+#               value: "alertes@example.com"
+#             - name: MAIL_TO
+#               value: "${LDAP_USER1_EMAIL}"
+#             - name: LLDAP_GROUP
+#               value: "jelly_admin"
+#       backoffLimit: 0
 
 ---
 apiVersion: batch/v1
 kind: CronJob
 metadata:
-  annotations:
-    argocd.argoproj.io/hook: PostSync
-    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
   labels:
     helm.toolkit.fluxcd.io/name: lldap
     helm.toolkit.fluxcd.io/namespace: lldap
